# Generated by Django 3.1.1 on 2021-02-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrastatic',
            name='script',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='extrastatic',
            name='static_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'CSS'), (2, 'HTML'), (3, 'Javascript')], default=1),
        ),
        migrations.AlterField(
            model_name='extrastatic',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
