# Generated by Django 3.1.1 on 2021-02-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expectedanswer',
            old_name='expected_result',
            new_name='expected_output',
        ),
    ]
