# Generated by Django 3.1.1 on 2021-02-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210221_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='output_interface',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Console'), (2, 'Web')], default=1),
        ),
    ]
