# Generated by Django 3.1.1 on 2021-02-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210224_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
