# Generated by Django 3.1.1 on 2021-02-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_lesson_output_interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('static_type', models.PositiveSmallIntegerField(choices=[(1, 'Css'), (2, 'Javascript')], default=1)),
                ('url', models.URLField(max_length=255)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_asset', to='app.lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
