# Generated by Django 3.1.1 on 2021-02-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_extrastatic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrastatic',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_static', to='app.lesson'),
        ),
    ]
